home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [

    path("", views.index, name='index'),
    path("about/", views.about, name='about'),
    path("contact/", views.contact, name='contact'),
    path("book/table", views.booking, name='book'),
    path("ratings/", views.rating, name='rate'),
    path("admin123/", views.admin_page, name='admin-pg'),

    path("register/", views.register, name='register'),
    path("login/", views.login_request, name='login'),
    path("logout/", views.logout_request, name='logout'),

]

hotel/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace="home")),
    path('menu/', include('order.urls', namespace="order")),

 ]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [

    path("", views.index, name='index'),
    path("add/", views.item_form, name='item-add'),
    path("edit/<int:pk>", views.item_edit, name='item-edit'),
    path("delete/<int:pk>", views.item_delete, name='item-del'),
    path("list/", views.item_list, name='item-list'),

    path("cart/add/<int:pk>", views.add_to_cart, name='cart-add'),
    path("cart/plus/<int:pk>", views.plus_to_cart, name='cart-plus'),
    path("cart/minus/<int:pk>", views.minus_to_cart, name='cart-minus'),

    path("cart/", views.cart_view , name='cart-view'),
    path("checkout/", views.checkout, name="checkout"),
    path("handlerequest/", views.handlerequest, name="HandleRequest"),
    #path("bill/", views.bill_view , name='bill-view'),

]

order/models.py
from django.db import models
import datetime
from home.models import person

class food_category(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class item(models.Model):
    name = models.CharField(max_length=40)
    category = models.ForeignKey(food_category , on_delete=models.CASCADE)
    price = models.CharField(max_length=6)

    def __str__(self):
        return self.name


class order(models.Model):
    user = models.ForeignKey(person, null=True, on_delete=models.SET_NULL)
    total = models.IntegerField(default=0)
    completed = models.BooleanField(default=False)


class orderitem(models.Model):
    item = models.ForeignKey(item, null=True, on_delete=models.SET_NULL)
    order = models.ForeignKey(order, null=True, on_delete=models.SET_NULL)
    quantity = models.IntegerField(default=0)



'''
class alumni(models.Model):
    name = models.CharField(max_length=40)
    father = models.CharField(max_length=40)
    e_num = models.CharField(max_length=10, blank=True, null=True )
    image = models.FileField(upload_to='alumni/' , blank=True, null=True)
    email = models.EmailField(max_length=254)
    phone = models.CharField(max_length=12)
    address1 = models.TextField()
    address2 = models.TextField()
    from1 = models.TextField()
    upto1 = models.TextField()
    job = models.TextField()

    def __str__(self):
        return self.name



class gallery_type(models.Model):
    name = models.CharField(max_length=  40)
    description = models.TextField(blank=True)
    type_image = models.FileField(upload_to='gallery/' , blank=True, null=True)

    def __str__(self):
        return self.name



class gallery (models.Model):
    name = models.CharField(max_length=40)
    category = models.ForeignKey(gallery_type , on_delete=models.CASCADE)
    dated_on = models.DateField(default=datetime.date.today)
    image = models.FileField(upload_to='gallery/' , blank=True, null=True)

    def __str__(self):
        return self.name


class article (models.Model):
    title = models.CharField(max_length=40)
    description = models.TextField(blank=True)
    author = models.CharField(max_length=40)
    author_post = models.CharField(max_length=40)
    dated_on = models.DateField(default=datetime.date.today)
    image = models.FileField(upload_to='article/' , blank=True, null=True)

    def __str__(self):
        return self.title



class news(models.Model):
    title = models.CharField(max_length=15)
    description = models.TextField(blank=True)
    date = models.DateField(default=datetime.date.today)
    news_image = models.FileField(upload_to='news/')
    news_file = models.FileField(upload_to='news/', blank=True)

    def __str__(self):
        return self.title
'''

order/forms.py
from django import forms
from .models import  item, food_category


class ItemForm(forms.ModelForm):
    class Meta:
        model = item
        fields = ('name', 'category', 'price' )

order/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.http import HttpResponse
from .models import item, food_category, orderitem, order
from .forms import ItemForm
from home.models import person

from django.views.decorators.csrf import csrf_exempt
#from paytm.payments import PaytmPaymentPage
#from paytm.payments import VerifyPaytmResponse,JsonResponse
from .Paytm import Checksum
# Create your views here.
from django.http import HttpResponse
MERCHANT_KEY = 'lE6YN@L!%4GBKg%I'


def index(request):
    all_cat = food_category.objects.all()
    list1 = []
    list2 = []
    i=1
    for cat  in all_cat:
        if i<6:
            li = item.objects.filter(category=cat)
            list1.append(li)
            i = i+1
        else:
            li = item.objects.filter(category=cat)
            list2.append(li)
    return render(request, 'order/index.html', {'list1':list1, 'list2':list2 })


def item_form(request):
    categorys = food_category.objects.all()
    if request.method == "POST":
        form = ItemForm(request.POST)
        if form.is_valid():
            form.save(True)
            return redirect('order:index')
        else:
            return HttpResponse("Nhi hua")
    return render(request, 'order/item_form.html', {'categorys':categorys })


def item_edit(request,pk):
    itm = item.objects.get(pk=pk)
    if request.method == "POST":
        name = request.POST.get('name')
        price = request.POST.get('price')
        itm.name = name
        itm.price = price
        itm.save()
        return redirect('order:item-list')
    return render(request, 'order/item_edit_form.html', {'item':itm })


def item_delete(request,pk):
    itm = item.objects.get(pk=pk)
    itm.delete()
    categorys = food_category.objects.all()
    items = []
    for cat in categorys:
        its = item.objects.filter(category=cat)
        for it in its:
            items.append(it)
    return render(request, 'order/item_list.html', {'items':items })


def item_list(request):
    categorys = food_category.objects.all()
    items = []
    for cat in categorys:
        its = item.objects.filter(category=cat)
        for it in its:
            items.append(it)
    return render(request, 'order/item_list.html', {'items':items })


def add_to_cart(request, pk):
    if request.user.is_authenticated:
        it = item.objects.get(pk=pk)
        prsn = person.objects.get(user=request.user)
        if order.objects.filter(user=prsn, completed=False).count() >0:
            oder = order.objects.get(user=prsn, completed=False)
        else:
            oder = order(user=prsn)
            oder.save()
        if orderitem.objects.filter(order=oder,item=it).count() >0:
            oi = orderitem.objects.get(order=oder,item=it)
            oi.quantity = oi.quantity + 1
        else:
            oi = orderitem(item=it, order=oder, quantity=1)
        oi.save()
        return redirect('order:index')
    return HttpResponse("Please Login to add items. ")


def plus_to_cart(request, pk):
    if request.user.is_authenticated:
        oi = orderitem.objects.get(pk=pk)
        oi.quantity = oi.quantity + 1
        oi.save()
        return redirect('order:cart-view')
    return HttpResponse("Please Login to add items. ")


def minus_to_cart(request, pk):
    if request.user.is_authenticated:
        oi = orderitem.objects.get(pk=pk)
        oi.quantity = oi.quantity - 1
        oi.save()
        if oi.quantity == 0 :
            oi.delete()
        return redirect('order:cart-view')
    return HttpResponse("Please Login to add items. ")



def cart_view(request):
    if request.user.is_authenticated:
        prsn = person.objects.get(user=request.user)
        if order.objects.filter(user=prsn, completed=False).count() >0:
            oder = order.objects.get(user=prsn, completed=False)
            items = orderitem.objects.filter(order=oder)
            totals=[]
            g_total = 0
            for itm in items:
                tot = int(itm.item.price) * int(itm.quantity)
                g_total = g_total + tot
                totals.append(tot)
            oder.total = g_total
            oder.save()
        else:
            return HttpResponse("Cart is Empty. ")
        xyz = zip(items, totals)
        return render(request, 'order/cart.html', {'prsn':prsn, 'items':xyz, 'g_total':g_total  })
    return HttpResponse("Please Login to view Cart. ")


def checkout(request):
    if request.user.is_authenticated:
        prsn = person.objects.get(user=request.user)
        if order.objects.filter(user=prsn, completed=False).count() >0:
            oder = order.objects.get(user=prsn, completed=False)
            param_dict = {
                'MID': 'ADdYJP68142813746242',
                'ORDER_ID': str(oder.id),
                'TXN_AMOUNT': str(oder.total),
                'CUST_ID': str(oder.user.id) ,
                'INDUSTRY_TYPE_ID': 'Retail',
                'WEBSITE': 'WEBSTAGING',
                'CHANNEL_ID': 'WEB',
                'CALLBACK_URL':'http://navdurga.pythonanywhere.com/menu/handlerequest/',
            }
            param_dict['CHECKSUMHASH'] = Checksum.generate_checksum(param_dict, MERCHANT_KEY)
            return render(request, 'order/paytm.html', {'param_dict': param_dict})
        else:
            return HttpResponse("Cart is Empty. ")
        return render(request, 'order/cart.html', {'prsn':prsn, 'order':oder   })
    return HttpResponse("Please Login to view Cart. ")


@csrf_exempt
def handlerequest(request):
    # paytm will send you post request here
    form = request.POST
    response_dict = {}
    for i in form.keys():
        response_dict[i] = form[i]
        if i == 'CHECKSUMHASH':
            checksum = form[i]
    verify = Checksum.verify_checksum(response_dict, MERCHANT_KEY, checksum)
    if verify:
        if response_dict['RESPCODE'] == '01':
            print('order successful')
            opk = response_dict['ORDERID']
            oder = order.objects.get(pk=opk)
            oder.completed = True
            oder.save()
        else:
            print('order was not successful because' + response_dict['RESPMSG'])
    return render(request, 'order/paymentstatus.html', {'response': response_dict})

order/templates/order/cart.html
{% extends 'base.html' %}

{% block head %}
    <title> Hotel Navdurga | Cart  </title>
{% endblock %}

{% block body %}


    <section class="contact spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-6 col-sm-5">

                         <h4>  Hello {{ prsn.name }} </h4>
                         <h3>  Your Food Cart </h3>
                         <br>

                          <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th> Sr. no. </th>
                                                <th> Item </th>
                                                <th> Price </th>
                                                <th> Quantity </th>
                                                <th> Total </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                              {% for item,total in items %}
                      <tr>
                              <td> {{ forloop.counter }}. </td>
                              <td> {{ item.item }} </td>
                              <td> {{ item.item.price }} </td>
                              <td>  <a href="{% url 'order:cart-minus' item.pk %}" > - </a>
                                    {{ item.quantity }}
                                    <a href="{% url 'order:cart-plus' item.pk %}" > + </a>
                              </td>
                              <td> {{ total }} </td>
                      </tr>
                             {% endfor %}

                      <tr>
                              <td colspan=4 > <center>  <strong> Total </strong> </center> </td>
                              <td> <strong> {{  g_total  }} </strong>  </td>
                      </tr>

                                        </tbody>
                                    </table>
                                </div>



<br>
     <a href="{% url 'order:checkout' %}">  Proceed To Pay </a>
            </div>
        </div>
        </div>
        </section>

{% endblock %}

order/templates/order/index.html
{% extends 'base.html' %}

{% block head %}
    <title> Hotel Navdurga | Menu  </title>
{% endblock %}

{% block body %}
    <section class="contact spad">
        <div class="container"  style="background-image: url('/static/img/menu-bg4.jpg'); background-repeat: repeat-y; background-size: contain;" >
                <h2> Our Menu </h2> <br>

            <div class="row">

                <div class="col-lg-6 col-md-6 col-sm-7" >
                          <div class="table-responsive" >
                            <table class="table" >
                                <tbody>
                    {% for list_item in list1 %}
                              <tr>  <td> <h4> {{ list_item.0.category }} </h4>  </td> </tr>
                    {% if request.user.is_authenticated %}
                            {% for item in list_item %}
                              <tr>
                              <td> {{ forloop.counter }}. </td>
                              <td> {{ item }}       </td>
                              <td> {{ item.price }} </td>
                              <td> <a href="{% url 'order:cart-add' item.pk %}" > Add </a> </td>
                              </tr>
                            {% endfor %}
                    {% else %}

                            {% for item in list_item %}
                              <tr>
                              <td> {{ forloop.counter }}. </td>
                              <td> {{ item }} </td>
                              <td> {{ item.price }} </td>
                              </tr>
                            {% endfor %}

                    {% endif %}
                    {% endfor %}
                             </tbody>
                             </table>
                             </div>
</div>
                <div class="col-lg-6 col-md-6 col-sm-7">
                    <div class="table-responsive" >
                            <table class="table" >
                                <tbody>
                    {% for list_item in list2 %}
                              <tr>  <td> <h4> {{ list_item.0.category }} </h4>  </td> </tr>
                    {% if request.user.is_authenticated %}
                            {% for item in list_item %}
                              <tr>
                              <td> {{ forloop.counter }}. </td>
                              <td> {{ item }}       </td>
                              <td> {{ item.price }} </td>
                              <td> <a href="{% url 'order:cart-add' item.pk %}" > Add </a> </td>
                              </tr>
                            {% endfor %}
                    {% else %}

                            {% for item in list_item %}
                              <tr>
                              <td> {{ forloop.counter }}. </td>
                              <td> {{ item }} </td>
                              <td> {{ item.price }} </td>
                              </tr>
                            {% endfor %}

                    {% endif %}
                    {% endfor %}
                             </tbody>
                             </table>
                             </div>
                </div>
            </div>
        </div>
    </section>

<br> <br> <br>

{% endblock %}

order/templates/order/item_edit_form.html
{% extends 'base.html' %}

{% block head %}
    <title> Hotel Navdurga | Menu  </title>
{% endblock %}

{% block body %}
<div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-5">
                <br> <br>
                <h3> Menu Item Edit Form  </h3> <br>
                <form  action="" method="post" >
                      {% csrf_token %}
                    <div class="row">
                      <div class="col-md-10">
                        <div class="form-group">
                          <label class="bmd-label-floating"> Item Name</label>
                          <input type="text" class="form-control" name="name"  value={{ item.name }} required>
                        </div>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-10">
                        <div class="form-group">
                          <label class="bmd-label-floating"> Item Price </label>
                          <input type="number" class="form-control" name="price" value={{ item.price }} required>
                        </div>
                      </div>
                    </div>
                    <button type="submit" class="btn btn-primary "> Save Changes </button>
                    <div class="clearfix"></div>
                  </form>
</div>
</div>
<br> <br> <br>

{% endblock %}

order/templates/order/item_form.html
{% extends 'base.html' %}

{% block head %}
    <title> Hotel Navdurga | Menu  </title>
{% endblock %}

{% block body %}
<div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-5">
                <br> <br>
                <h3> Menu Item Form  </h3>
                <form  action="" method="post" >
                      {% csrf_token %}
                    <div class="row">
                      <div class="col-md-10">
                        <div class="form-group">
                          <label class="bmd-label-floating"> Item Name</label>
                          <input type="text" class="form-control" name="name"  required>
                        </div>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-10">
                        <div class="form-group">
                          <label class="bmd-label-floating"> Choose Category </label> <br>
                          <select class="form-control" name="category"  required >
                         <option value selected> -----  </option>
                         {% for opt in categorys %}
                          <option value="{{ opt.id }}" >  {{ opt }}  </option>
                         {% endfor %}
                          </select>
                        </div>
                      </div>
                    </div>


                    <div class="row">
                      <div class="col-md-10">
                        <div class="form-group">
                          <label class="bmd-label-floating"> Item Price </label>
                          <input type="number" class="form-control" name="price"  required>
                        </div>
                      </div>
                    </div>
                    <button type="submit" class="btn btn-primary "> Add to Menu </button>
                    <div class="clearfix"></div>
                  </form>
</div>
</div>
<br> <br> <br>

{% endblock %}

order/templates/order/item_list.html
{% extends 'base.html' %}

{% block head %}
    <title> Hotel Navdurga | Menu  </title>
{% endblock %}

{% block body %}

<section class="contact spad">
        <div class="container">

                <div class="col-lg-6 col-md-6 col-sm-7">
                <h2>  Menu- List </h2>
                          <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th> Sr. no. </th>
                                                <th> Item </th>
                                                <th> Price </th>
                                                <th> Edit </th>
                                                <th> Delete </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                        {% for item in items %}
                          <tr>
                              <td> {{ forloop.counter }}. </td>
                              <td> {{ item }}       </td>
                              <td> {{ item.price }} </td>
                              <td> <a href="{% url 'order:item-edit' item.pk %}" > Edit </a> </td>
                              <td> <a href="{% url 'order:item-del' item.pk %}" > Delete </a> </td>
                          </tr>
                        {% endfor %}
                        </tbody>
                                    </table>
                          </div>
                </div>
        </div>
</section>

{% endblock %}

order/templates/order/paymentstatus.html
{% extends 'base.html' %}
{% block title%} My Awesome Cart Tracker{% endblock %}
{% block body %}
<div class="container">
    {{response}}
    <div class="col my-4">

        <h2>Payment status regarding your order Id {{response.ORDERID}}</h2>
        {% if response.RESPCODE == '01' %}
        ORDER SUCCESS
        {% else %}
        ORDER FAILURE
        {% endif%}

    </div>

</div>
{% endblock %}

order/templates/order/paytm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Paytm merchant payment page</title>
</head>
<body>
<h1>Redirecting you to the merchant....</h1>
<h1>Please do not refresh your page....</h1>
<form action="https://securegw-stage.paytm.in/theia/processTransaction" method="post" name="paytm">
    {% for key, value in param_dict.items %}
    <input type="hidden" name="{{key}}" value="{{value}}">
    {% endfor %}

</form>
</body>
<script>
document.paytm.submit()
</script>
</html>