home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [

    path("", views.index, name='index'),
    path("about/", views.about, name='about'),
    path("contact/", views.contact, name='contact'),
    path("book/table", views.booking, name='book'),
    path("ratings/", views.rating, name='rate'),
    path("admin123/", views.admin_page, name='admin-pg'),

    path("register/", views.register, name='register'),
    path("login/", views.login_request, name='login'),
    path("logout/", views.logout_request, name='logout'),

]

hotel/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace="home")),
    path('menu/', include('order.urls', namespace="order")),

 ]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [

    path("", views.index, name='index'),
    path("add/", views.item_form, name='item-add'),
    path("edit/<int:pk>", views.item_edit, name='item-edit'),
    path("delete/<int:pk>", views.item_delete, name='item-del'),
    path("list/", views.item_list, name='item-list'),

    path("cart/add/<int:pk>", views.add_to_cart, name='cart-add'),
    path("cart/plus/<int:pk>", views.plus_to_cart, name='cart-plus'),
    path("cart/minus/<int:pk>", views.minus_to_cart, name='cart-minus'),

    path("cart/", views.cart_view , name='cart-view'),
    path("checkout/", views.checkout, name="checkout"),
    path("handlerequest/", views.handlerequest, name="HandleRequest"),
    #path("bill/", views.bill_view , name='bill-view'),

]

templates/about.html
{% extends 'base.html' %}

{% block head %}
    <title> Hotel Navdurga | About  </title>
{% endblock %}

    {% block nav %}
                            <nav class="header__menu">
                                <ul class="menu__class">
                                    <li><a href="{% url 'home:index' %}">Home</a></li>

                                    <li class="active"><a href="{% url 'home:about' %}">About Us</a></li>
                                    <li><a href="#"> Services </a>
                                        <ul class="dropdown">
                                            <li><a href="#"> Food Court  </a></li>
                                            <li><a href="#"> Rooms       </a></li>
                                            <li><a href="{% url 'order:index' %}"> Menu </a></li>
                                            <li><a href="{% url 'order:index' %}"> Order Food </a></li>
                                        </ul>
                                    </li>

                                    <li><a href="#"> My Account </a>
                                        <ul class="dropdown">
                                         {% if request.user.is_authenticated %}
                                            <li> <a href="{% url 'home:logout' %}"> Logout </a></li>
                                         {% else %}
                                            <li><a href="{% url 'home:login' %}"> Login </a> </li>
                                            <li><a href="{% url 'home:register' %}"> Register </a> </li>
                                         {% endif %}

                                            <li><a href="{% url 'order:cart-view' %}"> My Cart </a></li>
                                            <li><a href="#"> My Orders  </a></li>
                                        </ul>
                                    </li>

                                    <li><a href="{% url 'home:contact' %}"> Contact </a></li>
                                </ul>
                            </nav>

                                {% endblock %}



{% block body %}

    <div class="breadcrumb-option set-bg" data-setbg="/static/img/hotel/hotel6b.jpg" style="height:70%  opacity:0.3;" >
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h1>About Us</h1>
                        <div class="breadcrumb__links">
                            <a href="{% url 'home:index' %}">Home</a>
                            <span>About Us</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- About Section Begin -->
    <section class="about spad" style="padding-top:50px;">
        <div class="container">
            <div class="about__content">
                <div class="row">
                    <div class="col-lg-5">
                        <div class="section-title">
                            <img src="/static/img/about.png" >
                        </div>
                    </div>
                    <div class="col-lg-7">
                        <div class="about__text">
                            <h4>  Welcome to Hotel Navdurga </h4>
                            <p> Hotel Navdurga is a deluxe restaurant located in Aau village. We are conveniently located in the
                                downtown of Jodhpur Near Jaipur-Jaiselmer Highway.
                                Our hotel is at mid-way of the highway , while going to Jaiselmer we will provide you with best food and
                                accomodation.  Our location is just perfect for the travelers interested in shopping
                                as we are near the Aau markets.
                            </p>
                            <p> We offer a classic mix of luxurious comfort, reasonable pricing and beautiful nature.
                                Navdurga Hotel has a quiet, peaceful and posh locality free from air and noise pollution.
                            </p>
                            <p> Our restaurant is open for breakfast, lunch and dinner to serve you. While we present a broad range of traveler
                                and global favorites, we specialize in traditional Rajasthan cuisine. A great many vegetarian options are also
                                available. 360 view of the city is available from our restaurant.
                            </p>
                        </div>
                    </div>
                </div>
            </div>




            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <div class="services__item">
                        <img src="/static/img/services/services-3.png" alt="">
                        <h4> Parking Space </h4>
                        <p> We are offering enough space to rest your vehicle without any difficulty with best security services.
                        </p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <div class="services__item">
                        <img src="/static/img/services/services-2.png" alt="">
                        <h4> Food Delivery  </h4>
                        <p> Home delivery of food services are available for local customers with in Aau area.
                            Please check the <a href="#" style="color:orange;" >  Menu </a> to know more.
                        </p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <div class="services__item">
                        <img src="/static/img/services/services-1.png" alt="">
                        <h4> Free WiFi </h4>
                        <p>
                            Free wifi is available in lobby area and restaurant for customers which help you to stay connected
                        </p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <div class="services__item">
                        <img src="/static/img/services/services-4.png" alt="">
                        <h4> Coffee  </h4>
                        <p>
                            We are offering world class coffee which help you to kick start a great day of your journey
                        </p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <div class="services__item">
                        <img src="/static/img/services/services-5.png" alt="">
                        <h4> Food Packaging </h4>
                        <p>
                            We offer a service of packing your meal to save your time of tour
                        </p>
                    </div>
                </div>

                <div class="col-lg-4 col-md-4 col-sm-6">
                    <div class="services__item">
                        <img src="/static/img/services/services-6.png" alt="">
                        <h4> Restaurant </h4>
                        <p>
                            The food court in hotel offers a great taste and finger licking meal to our customers
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About Section End -->

    <!-- Chooseus Section Begin -->
    <div class="chooseus spad set-bg" data-setbg="/static/img/chooseus-bg.jpg">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-8 text-center">
                    <div class="chooseus__text">
                        <div class="section-title">
                            <h5> You are Welcome </h5>
                            <h2> Visit us now to get the latest deals and reserve a table you have a plan to visit us . </h2>
                        </div>
                        <a href="{% url 'home:book' %}" class="primary-btn">Book Now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Chooseus Section End -->

    <!-- History Section Begin -->
    <section class="history spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title history-title">
                        <h5> Our Place </h5>
                        <h2> Explore Our Hotel </h2>
                    </div>
                </div>
            </div>
                        <div class="history__content">
                <div class="row">
                    <div class="col-lg-5 col-md-5">
                        <div class="history__item left__item">
                            <div class="history__date"></div>

                            <h4> AC Halls </h4>
                            <img src="/static/img/hotel/hotel1.jpg" alt="">
                            <p> Fully air conditioned hall with 8 tables </p>
                        </div>
                        <!--div class="history__item left__item mb-0">
                            <div class="history__date"></div>

                            <h4> Front Office </h4>
                            <img src="/static/img/hotel/hotel2.jpg" alt="">
                            <p> Fully equipped front office and ready to eat snacks </p>
                        </div-->
                    </div>
                    <div class="col-lg-5 offset-lg-2 col-md-5 offset-md-2">
                        <div class="history__item right__first__item" style="margin-bottom:0;">
                            <div class="history__date"></div>

                            <h4> Restaurant </h4>
                            <img src="/static/img/hotel/hotel4.jpg" alt="">
                            <p> Nice and clean furnished restaurant </p>
                        </div>
                        <!--div class="history__item mb-0">
                            <div class="history__date"></div>

                            <h4> Food Court  </h4>
                            <img src="/static/img/hotel/hotel4.jpg" alt="">
                            <p>   </p>
                        </div-->
                    </div>
                </div>
            </div>
            <div class="history__content">
                <div class="row">
                    <div class="col-lg-5 col-md-5">
                        <div class="history__item left__item">
                            <div class="history__date"></div>

                            <h4> Party Hall </h4>
                            <img src="/static/img/hotel/hotel5.jpeg" alt="">
                            <p> We provide a party hall with all arrangements for you to celebrate your day </p>
                        </div>
                        <div class="history__item left__item mb-0">
                            <div class="history__date"></div>

                            <h4> Party Hall </h4>
                            <img src="/static/img/hotel/hotel6.jpeg" alt="">
                            <p> We provide a party hall with all arrangements for you to celebrate your day  </p>
                        </div>
                    </div>
                    <div class="col-lg-5 offset-lg-2 col-md-5 offset-md-2">
                        <div class="history__item right__first__item">
                            <div class="history__date"></div>

                            <h4> Private AC Hall </h4>
                            <img src="/static/img/hotel/hotel7.jpeg" alt="">
                            <p>  We are providing a luxurious ac hall to make your visit comfortable.  </p>
                        </div>
                        <div class="history__item mb-0">
                            <div class="history__date"></div>

                            <h4> Furnished Lightings </h4>
                            <img src="/static/img/hotel/hotel8.jpg" alt="">
                            <p> We offer you a  new technology of lighting which make you  heavenly feeling  </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- History Section End -->
<br> <br>

{% endblock %}

templates/admin_page.html
{% extends 'base.html' %}

{% block head %}
    <title> Hotel Navdurga | Admin Page  </title>
{% endblock %}

{% block body %}

    <!-- About Section Begin -->
    <section class="about spad">
        <div class="container">
            <div class="about__content">
                <div class="row">
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-7">
                        1. <a href="{% url 'order:item-list' %}">  View Menu List </a> <br>
                        2. <a href="{% url 'order:item-add' %}">  Add Item to Menu </a> <br> <br>

                        3. <a href="#">  View all Orders </a> <br>
                        4. <a href="#">  View all Bookings </a> <br> <br>

                        <br> <br> <br>
                        <br> <br> <br>
                        <br> <br> <br>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About Section End -->

<br> <br>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Hiroto Template">
    <meta name="keywords" content="Hiroto, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block head %}
    <title> Hotel Navdurga </title>
    {% endblock %}


    <!-- Css Styles -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="/static/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="/static/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="/static/css/style.css" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__logo">
            <a href="{% url 'home:index' %}"><img src="/static/img/logo.jpg" alt="" style="min-width:150px;"></a>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="offcanvas__btn__widget">
            <a href="#">Book Now <span class="arrow_right"></span></a>
        </div>
        <div class="offcanvas__widget">
            <ul>
                <li><span class="icon_pin_alt"></span> Nagaur Road, Aau </li>
                <li><span class="icon_phone"></span> +91 94922 98000 </li>
                <li><span class="icon_phone"></span> +91 91164 55151 </li>

            </ul>
        </div>
        <!--div class="offcanvas__language">
            <img src="/static/img/lan.png" alt="">
            <span>English</span>
            <i class="fa fa-angle-down"></i>
            <ul>
                <li>English</li>
                <li>Bangla</li>
            </ul>
        </div-->
        <div class="offcanvas__auth">
            <ul>
                <li><a href="#">Login</a></li>
                <li><a href="#">Register</a></li>
            </ul>
        </div>
    </div>
    <!-- Offcanvas Menu End -->

    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7">
                        <ul class="header__top__widget">
                            <li><span class="icon_pin_alt"></span>  Nagaur Road, Aau  </li>
                            <li><span class="icon_phone"></span> +91 94922 98000</li>
                            <li><span class="icon_phone"></span> +91 91164 55151</li>
                        </ul>
                    </div>
                    <div class="col-lg-5">
                        <div class="header__top__right">
                            <div class="header__top__auth">
                                <ul>
                                    <li><a href="{% url 'home:login' %}">Login</a></li>
                                    <li><a href="{% url 'home:register' %}">Register</a></li> to Order Now !!!
                                </ul>
                            </div>
                            <!--div class="header__top__language">
                                <img src="/static/img/lan.png" alt="">
                                <span>English</span>
                                <i class="fa fa-angle-down"></i>
                                <ul>
                                    <li>English</li>
                                    <li>Bangla</li>
                                </ul>
                            </div-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header__nav__option">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2">
                        <div class="header__logo">
                            <a href="{% url 'home:index' %}"> <img src="/static/img/logo.jpg" alt="" style="min-width:250px; max-width:300px;"></a>
                        </div>
                    </div>
                    <div class="col-lg-10">
                        <div class="header__nav">


                                {% block nav %}
                            <nav class="header__menu">
                                <ul class="menu__class">
                                    <li class="active"><a href="{% url 'home:index' %}">Home</a></li>

                                    <li><a href="{% url 'home:about' %}">About Us</a></li>
                                    <li><a href="#"> Services </a>
                                        <ul class="dropdown">
                                            <li><a href="#"> Food Court  </a></li>
                                            <li><a href="#"> Rooms       </a></li>
                                            <li><a href="{% url 'order:index' %}"> Menu </a></li>
                                            <li><a href="{% url 'order:index' %}"> Order Food </a></li>
                                        </ul>
                                    </li>

                                    <li><a href="#"> My Account </a>
                                        <ul class="dropdown">
                                         {% if request.user.is_authenticated %}
                                            <li> <a href="{% url 'home:logout' %}"> Logout </a></li>
                                         {% else %}
                                            <li><a href="{% url 'home:login' %}"> Login </a> </li>
                                            <li><a href="{% url 'home:register' %}"> Register </a> </li>
                                         {% endif %}

                                            <li><a href="{% url 'order:cart-view' %}"> My Cart </a></li>
                                            <li><a href="#"> My Orders  </a></li>
                                        </ul>
                                    </li>

                                    <li><a href="{% url 'home:contact' %}"> Contact </a></li>
                                </ul>
                            </nav>

                                {% endblock %}


                            <div class="header__nav__widget">
                                <a href="{% url 'home:book' %}" >Book Now <span class="arrow_right"></span></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="canvas__open">
                    <span class="fa fa-bars"></span>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Section End -->

    {% block body %}

    {% endblock %}


    <!-- Footer Section Begin -->
    <footer class="footer set-bg" data-setbg="/static/img/footer-bg.jpg">
        <div class="container">
            <div class="footer__content">
                <div class="row">
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="footer__about">
                            <div class="footer__logo">
                                <a href="#"> <img src="/static/img/logo.jpg" alt=""> </a>
                            </div>
                            <h4> +91 94922 98000 </h4>
                            <h4> +91 91164 55151 </h4>
                            <h4> Nagaur Road, Aau </h4>
                        </div>
                    </div>
                    <div class="col-lg-3 offset-lg-1 col-md-5 offset-md-1 col-sm-6">
                        <div class="footer__widget">
                            <h4> Quick Links </h4>
                            <ul>
                                <li><a href="{% url 'home:index' %}">    Home      </a></li>
                                <li><a href="{% url 'order:index' %}">   Order Food </a></li>
                                <li><a href="{% url 'home:about' %}">    About   </a></li>
                                <li><a href="#">Review</a></li>
                                <li><a href="{% url 'home:contact' %}">  Contact   </a></li>
                            </ul>
                            <ul>
                                <li><a href="#">Services</a></li>
                                <li><a href="#">Our Room</a></li>
                                <li><a href="#">Restaurants</a></li>
                                <li><a href="#">Payments</a></li>
                                <li><a href="#">Events</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-8 col-sm-12">
                        <div class="footer__newslatter">
                            <h4> Rate Our Services </h4>
                            <form action="#">
                                <input type="text" placeholder="Your E-mail Address">
                                <button type="submit">Subscribe</button>
                            </form>
                        </div>
                        <div class="footer__about">
                             <div class="footer__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                <a href="#"><i class="fa fa-youtube-play"></i></a>
                            </div>

                        </div>
                    </div>


                </div>
            </div>
            <div class="footer__copyright">
                <div class="row">
                    <div class="col-lg-7 col-md-7">
                        <div class="footer__copyright__text">
                            <p>Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Srijan Tech Solutions  </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Js Plugins -->
    <script src="/static/js/jquery-3.3.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/jquery.nice-select.min.js"></script>
    <script src="/static/js/jquery-ui.min.js"></script>
    <script src="/static/js/jquery.slicknav.js"></script>
    <script src="/static/js/owl.carousel.min.js"></script>
    <script src="/static/js/main.js"></script>
</body>

</html>

templates/contact.html
{% extends 'base.html' %}

{% block head %}
    <title> Hotel Navdurga | Contact  </title>
{% endblock %}

    {% block nav %}
                            <nav class="header__menu">
                                <ul class="menu__class">
                                    <li><a href="{% url 'home:index' %}">Home</a></li>

                                    <li><a href="{% url 'home:about' %}">About Us</a></li>
                                    <li><a href="#"> Services </a>
                                        <ul class="dropdown">
                                            <li><a href="#"> Food Court  </a></li>
                                            <li><a href="#"> Rooms       </a></li>
                                            <li><a href="{% url 'order:index' %}"> Menu </a></li>
                                            <li><a href="{% url 'order:index' %}"> Order Food </a></li>
                                        </ul>
                                    </li>

                                    <li><a href="#"> My Account </a>
                                        <ul class="dropdown">
                                         {% if request.user.is_authenticated %}
                                            <li> <a href="{% url 'home:logout' %}"> Logout </a></li>
                                         {% else %}
                                            <li><a href="{% url 'home:login' %}"> Login </a> </li>
                                            <li><a href="{% url 'home:register' %}"> Register </a> </li>
                                         {% endif %}

                                            <li><a href="{% url 'order:cart-view' %}"> My Cart </a></li>
                                            <li><a href="#"> My Orders  </a></li>
                                        </ul>
                                    </li>

                                    <li class="active"><a href="{% url 'home:contact' %}"> Contact </a></li>
                                </ul>
                            </nav>

{% endblock %}

{% block body %}

    <!-- Map Begin -->
    <div class="map">

     <iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=Hotel%20Navdurga%20Nagaur%20Road%20Aau,%20Rajasthan&t=&z=15&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
    </div>
    <!-- Map End -->

    <!-- Contact Section Begin -->
    <section class="contact spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-6 col-sm-5">
                    <div class="contact__widget">
                        <div class="contact__widget__item">
                            <h4>Contact Us</h4>
                            <ul>
                                <li> +91 91164 55151 </li>
                                <li> +91 94922 98000 </li>
                            </ul>
                        </div>
                        <div class="contact__widget__item">
                            <h4>Address</h4>
                            <p>  Nagaur Road , Aau <br> Rajasthan </p>
                        </div>
                        <div class="contact__widget__time">
                            <h4>Opentime</h4>
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="contact__widget__time__item">
                                        <ul>
                                            <li>Monday - Friday</li>
                                            <li><span> 10 am - 9 pm </span></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="contact__widget__time__item">
                                        <ul>
                                            <li>Saturday - Sunday</li>
                                            <li><span> 9 am - 11 pm</span></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 offset-lg-1 col-md-6 col-sm-7">
                    <div class="contact__form">
                        <h2>Your question?</h2>
                        <form action="#">
                            <input type="text" placeholder="Your Name">
                            <input type="text" placeholder="Email">
                            <textarea placeholder="Your Message"></textarea>
                            <button type="submit">Send Message</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->



{% endblock %}